FROM node:18-alpine

WORKDIR /usr/src/app

ARG PAYPAL_SANDBOX
ARG NEXT_PUBLIC_PAYPAL_CLIENT_ID
ARG PAYPAL_CLIENT_SECRET
ARG PAYPAL_AUTH_WEBHOOK_ID

COPY package*.json ./
RUN npm ci

EXPOSE 8080

ENV HOST=0.0.0.0
ENV PORT=8080
ENV PAYPAL_SANDBOX=$PAYPAL_SANDBOX
ENV NEXT_PUBLIC_PAYPAL_CLIENT_ID=$NEXT_PUBLIC_PAYPAL_CLIENT_ID
ENV PAYPAL_CLIENT_SECRET=$PAYPAL_CLIENT_SECRET
ENV PAYPAL_AUTH_WEBHOOK_ID=$PAYPAL_AUTH_WEBHOOK_ID

COPY . ./
RUN npm run build

CMD [ "npm", "start" ]